name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
        puppet:
          - "~> 8.0"
          - "~> 7.24"
          - "~> 6.29"
        exclude:
          - ruby: "3.0"
            puppet: "~> 8.0"
          - ruby: "2.7"
            puppet: "~> 8.0"
          - ruby: "2.6"
            puppet: "~> 8.0"
          - ruby: "2.5"
            puppet: "~> 8.0"

          - ruby: "2.6"
            puppet: "~> 7.24"
          - ruby: "2.5"
            puppet: "~> 7.24"

          - ruby: "3.2"
            puppet: "~> 6.29"
          - ruby: "3.1"
            puppet: "~> 6.29"
          - ruby: "3.0"
            puppet: "~> 6.29"

    name: "Ruby ${{ matrix.ruby }} - Puppet ${{ matrix.puppet }}"
    env:
      PUPPET_VERSION: ${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build gem
        run: gem build *.gemspec
      - name: Run tests
        run: bundle exec rake spec
  tests:
    needs:
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
